name: Frontend Build Check

on:
  push:
  pull_request:

jobs:
  build-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json
            frontend/package-lock.json
            frontend-sld/package-lock.json

      - name: Install React Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build React Application
        working-directory: ./frontend
        run: npm run build

      - name: Install Solid Dependencies
        working-directory: ./frontend-sld
        run: npm ci

      - name: Build Solid Application
        working-directory: ./frontend-sld
        run: npm run build