name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - Frontend Build Check
      - Backend Tests
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: /tmp/ssh_key
          port: 22
          script: |
            cd ~/m-project-2

            pm2 stop didyoudoityet-api || true

            git pull origin main
            
            rm -rf node_modules

            echo "Checking..."
            ls -ld node_modules || echo "node_modules does not exist"

            npm ci

            cd frontend
            npm run build || exit 1
            sudo cp -r build/* /var/www/didyoudoityet/

            cd ../frontend-sld
            npm run build || exit 1

            cd ../frontend-htmx
            npm run build || exit 1
            # HTMX is server-side rendered, no static files to copy

            cd ..

            pm2 start didyoudoityet-api
            pm2 start didyoudoityet-htmx
            pm2 save